# Generated by Django 6.0.1 on 2026-02-13 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncers', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouncerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('aadhar_photo', models.ImageField(upload_to='aadhar_photos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bouncer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='bouncers.bouncerprofile')),
            ],
        ),
    ]
