# Generated by Django 6.0.1 on 2026-02-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouncers', '0003_bouncerverificationrequest'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.customerprofile'),
        ),
    ]
